# -*- coding: utf-8 -*-
# Base de dados: Cursos online de ingles cadastrados no site
import os

from pymongo import MongoClient, ASCENDING

DB_HOST = os.environ.get('DB_HOST', 'localhost')
DB_PORT = os.environ.get('DB_PORT', 27017)
DB_NAME = os.environ.get('DB_NAME', 'paloma')


class DataBase():

    def client(self, collection):
        client = MongoClient(DB_HOST, int(DB_PORT))
        db = client[DB_NAME]
        return db[collection]


db = DataBase()

collection = 'language_ingles'

courses = [
    {
        "name": "Duolingo",
        "based": ["exemplo", "exercicio_interativo"],
        "price_real": [0.0],
        "price_dolar": [0.0],
        "dynamic": ["curso_livre"],
        "platform": ["android_online", "ios_online"],
        "url": "https://www.duolingo.com/pt",
        "extra": ["comunicacao_alunos"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "Memrise",
        "based": ["exemplo", "exercicio_interativo"],
        "price_real": [0.0],
        "price_dolar": [0.0, 9.0, 54.0],
        "dynamic": ["curso_livre"],
        "platform": ["android_online", "ios_online", "android_offline",
                     "ios_offline", "desktop_online", "desktop_offline"],
        "url": "https://www.memrise.com/",
        "extra": ["selecao_nivel", "comunicacao_alunos"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "Live Mocha",
        "based": ["texto", "video_aula", "exemplo", "exercicio_interativo"],
        "price_real": [0.0],
        "dynamic": ["curso_livre"],
        "platform": ["desktop_online"],
        "url": "http://livemocha.com/",
        "extra": ["selecao_nivel", "professor", "comunicacao_alunos"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "IBEU",
        "based": ["texto", "video_aula", "exemplo", "exercicio_interativo"],
        "price_real": [183.0],
        "dynamic": ["tempo_definido"],
        "platform": ["android_online", "ios_online", "desktop_online"],
        "url": "http://inglesonline.ibeu.org.br/site/",
        "extra": ["selecao_nivel", "professor", "comunicacao_alunos"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "Busuu",
        "based": ["texto", "exemplo", "exercicio_interativo"],
        "price_real": [0.0, 7.0, 9.0, 14.0, 24.0],
        "dynamic": ["curso_livre"],
        "platform": ["android_online", "ios_online", "desktop_online"],
        "url": "https://www.busuu.com/pt/",
        "extra": ["selecao_nivel", "comunicacao_alunos"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "English Town",
        "based": ["texto", "video_aula", "exemplo", "exercicio_interativo"],
        "price_real": [139.0, 210.0],
        "dynamic": ["curso_livre"],
        "platform": ["android_online", "ios_online", "desktop_online"],
        "url": "http://www.englishtown.com.br/",
        "extra": ["selecao_nivel", "professor", "comunicacao_alunos"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "English Up",
        "based": ["texto", "video_aula", "exemplo", "exercicio_interativo"],
        "price_real": [200.0, 300.0, 400.0, 500.0],
        "dynamic": ["tempo_definido"],
        "platform": ["desktop_online"],
        "url": "http://www.englishup.com.br/",
        "extra": ["selecao_nivel", "professor", "comunicacao_alunos"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "UOL Curso de Ingles",
        "based": ["texto", "video_aula", "exemplo", "exercicio_interativo"],
        "price_real": [39.0, 79.0],
        "dynamic": ["curso_livre", "tempo_definido"],
        "platform": ["desktop_online", "desktop_offline"],
        "url": "http://cursodeingles.uol.com.br/",
        "extra": ["selecao_nivel", "professor", "comunicacao_alunos"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "Cursos 24 Horas",
        "based": ["texto", "video_aula", "exemplo", "exercicio_interativo"],
        "price_real": [30.0],
        "dynamic": ["curso_livre", "tempo_definido"],
        "platform": ["desktop_online"],
        "url": "http://www.cursos24horas.com.br/",
        "extra": ["selecao_nivel", "professor", "comunicacao_alunos"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "Prime cursos",
        "based": ["texto", "exemplo"],
        "price_real": [0.0],
        "dynamic": ["curso_livre", "tempo_definido"],
        "platform": ["desktop_online"],
        "url": "https://www.primecursos.com.br",
        "extra": ["selecao_nivel"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "Open english",
        "based": ["texto", "video_aula", "exemplo", "exercicio_interativo"],
        "price_real": [147.0],
        "dynamic": ["curso_livre"],
        "platform": ["desktop_online"],
        "url": "http://www.openenglish.com.br/",
        "extra": ["selecao_nivel", "professor"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "Ingles do Jerry",
        "based": ["video_aula", "exemplo"],
        "price_real": [0.0, 134.0],
        "dynamic": ["curso_livre", "tempo_definido"],
        "platform": ["desktop_online", "desktop_offline"],
        "url": "http://inglesdojerry.com.br/",
        "extra": ["professor"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "Babbel",
        "based": ["exemplo", "exercicio_interativo"],
        "price_real": [12.0, 15.0, 23.0],
        "dynamic": ["curso_livre", "inicioDefinido"],
        "platform": ["desktop_online", "android_online"],
        "url": "https://pt.babbel.com/",
        "extra": ["selecao_nivel"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "Iped idiomas",
        "based": ["video_aula"],
        "price_real": [8.0, 12.0, 33.0],
        "dynamic": ["curso_livre", "tempo_definido"],
        "platform": ["desktop_online"],
        "url": "https://www.iped.com.br/idiomas",
        "extra": ["selecao_nivel", "comunicacao_alunos"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "Ingles Curso",
        "based": ["texto", "video_aula", "exemplo", "exercicio_interativo"],
        "price_real": [0.0],
        "dynamic": ["curso_livre"],
        "platform": ["desktop_online"],
        "url": "http://www.inglescurso.net.br/",
        "extra": ["selecao_nivel"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "Aba English",
        "based": ["texto", "video_aula", "exemplo", "exercicio_interativo"],
        "price_real": [0.0, 45.0, 58.0, 66.0, 90.0],
        "dynamic": ["curso_livre"],
        "platform": ["desktop_online", "android_online", "ios_online"],
        "url": "http://www.abaenglish.com/pt/",
        "extra": ["selecao_nivel", "professor"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "Learn American English",
        "based": ["texto", "video_aula", "exemplo"],
        "price_real": [0.0],
        "dynamic": ["curso_livre"],
        "platform": ["desktop_online"],
        "url": "http://www.learnamericanenglishonline.com/",
        "extra": ["selecao_nivel"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "1- Language",
        "based": ["texto", "exemplo", "exercicio_interativo"],
        "price_real": [0.0],
        "dynamic": ["curso_livre"],
        "platform": ["desktop_online"],
        "url": "http://www.1-language.com/",
        "extra": ["selecao_nivel"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "Usa Learns",
        "based": ["texto", "video_aula", "exemplo", "exercicio_interativo"],
        "price_real": [0.0, 6.0],
        "dynamic": ["curso_livre"],
        "platform": ["desktop_online", "android_online", "ios_online"],
        "url": "http://www.usalearns.org/",
        "extra": ["selecao_nivel"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "Petra Lingua",
        "based": ["texto", "video_aula", "exemplo", "exercicio_interativo"],
        "price_real": [89.0],
        "dynamic": ["curso_livre"],
        "platform": ["desktop_online", "desktop_offline",
                     "android_online", "android_offline", "ios_online", "ios_offline"],
        "url": "http://www.petralingua.com/pt/",
        "extra": [],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "5 minute english",
        "based": ["texto", "exemplo", "exercicio_interativo"],
        "price_real": [0.0],
        "dynamic": ["curso_livre"],
        "platform": ["desktop_online"],
        "url": "http://www.5minuteenglish.com/",
        "extra": [],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "Anki",
        "based": ["texto", "exemplo"],
        "price_real": [0.0],
        "dynamic": ["curso_livre"],
        "platform": ["desktop_online", "desktop_offline", "android_online",
                     "android_offline", "ios_online", "ios_offline"],
        "url": "http://ankisrs.net/",
        "extra": ["selecao_nivel"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    },
    {
        "name": "Speaking Your Best Inc",
        "based": ["video_aula"],
        "price_dolar": [125.0],
        "dynamic": ["curso_livre", "tempo_definido"],
        "platform": ["desktop_online", "desktop_offline"],
        "url": "http://www.speakingyourbest.com/",
        "extra": ["professor"],
        "description": "preecher",
        "rate": 0.0,
"count": 0,
    }
]

db.client(collection).remove({})

for course in courses:
    db.client(collection).insert_one(course)
db.client(collection).create_index([('name', ASCENDING)], unique=True)
